name: pythonApp

on: push
jobs:
  PushToDockerHub:
    runs-on: self-hosted
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4.4.0
    - name: Docker Login
      uses: docker/login-action@v4.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: build image
      run: |
        docker build -t spotifytoyoutube:${GITHUB_RUN_NUMBER} .
        docker tag spotifytoyoutube:${GITHUB_RUN_NUMBER} tunaola/babzmann-deploy:spotifytoyoutube_${GITHUB_RUN_NUMBER}
        docker push tunaola/babzmann-deploy:spotifytoyoutube_${GITHUB_RUN_NUMBER}

  pushToECRPublic:
    needs: PushToDockerHub
    runs-on: self-hosted
    steps:
    
    - name: LoginToPublicECR
      uses: docker/login-action@v4.6.0
      with:
        registry: public.ecr.aws
        username: ${{ secrets.ACCESS_KEY }} 
        password: ${{ secrets.SECRET_ACCESS_KEY }}
      env:
        aws-region: ${{ secrets.REGION }}
    - name: Code checkout
      uses: actions/checkout@v4.4.0

    - name: build and push image for to public ECR
      run: |
        docker build -t spotifytoyoutube_pub .
        docker tag spotifytoyoutube_pub:latest public.ecr.aws/o8b9t3u4/spotifytoyoutube_pub:${GITHUB_RUN_NUMBER}
        docker push public.ecr.aws/o8b9t3u4/spotifytoyoutube_pub:${GITHUB_RUN_NUMBER}
        
  pushToECRPrivate:
    needs: PushToDockerHub
    runs-on: self-hosted
    steps:
    
    - name: Code checkout
      uses: actions/checkout@v4.4.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Login to Amazon Private ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Image to Private ECR
      env:
      
        #ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

        ECR_REGISTRY: 496777888499.dkr.ecr.eu-west-2.amazonaws.com
        ECR_REPOSITORY: spotifytoyoutube_private 
      run: |
        docker build -t spotifytoyoutube_priv .
        docker tag spotifytoyoutube_priv:latest $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_RUN_NUMBER}

        
